export { default as  Jumbotron} from "./jumbotron/index"
export { default as  Footer} from "./Footer"
export {default as Accordian} from "./accordian"
export {default as Optform} from "./opt-form"
export {default as   Header } from "./header"
export {default as   Feature } from "./feature"
export {default as   Form } from "./form"
export {default as Profiles}from "./profiles"
export {default as Loading}from "./loading"
export {default as Card} from "./card"
export {default as Player} from "./Player"
